version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    ports:
      - "26657:26657"
      - "26656:26656"
      - "9090:9090"
    volumes:
      - ./data/node1:/root/.evmosd
      - ./genesis.json:/root/.evmosd/config/genesis.json
    networks:
      - evmosnet
    command: sh /heliades.sh

  node2:
    build: .
    container_name: node2
    ports:
      - "26667:26657"
      - "26666:26656"
      - "9091:9090"
    volumes:
      - ./data/node2:/root/.evmosd
      - ./genesis.json:/root/.evmosd/config/genesis.json
    networks:
      - evmosnet
    command: sh /heliades.sh

  node3:
    build: .
    container_name: node3
    ports:
      - "26677:26657"
      - "26676:26656"
      - "9092:9090"
    volumes:
      - ./data/node3:/root/.evmosd
      - ./genesis.json:/root/.evmosd/config/genesis.json
    networks:
      - evmosnet
    command: sh /heliades.sh

networks:
  evmosnet:
    driver: bridge
